/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS
     Modified to read values from Vite environment variables.

     Provide these in a `.env` or `.env.local` file at project root:
     VITE_SUPABASE_PROJECT_ID=your-project-id
     VITE_SUPABASE_ANON_KEY=your-public-anon-key
     VITE_EDGE_FN_NAME=your-edge-function-name (optional)
*/

function requiredEnv(key: string, val: string | undefined): string {
    if (!val) throw new Error(`Missing required env var: ${key}`)
    return val
}

export const projectId: string = requiredEnv(
    'VITE_SUPABASE_PROJECT_ID',
    import.meta.env.VITE_SUPABASE_PROJECT_ID as unknown as string | undefined
)

export const publicAnonKey: string = requiredEnv(
    'VITE_SUPABASE_ANON_KEY',
    import.meta.env.VITE_SUPABASE_ANON_KEY as unknown as string | undefined
)

// Client-side edge function name (used when calling /functions/v1/<name>/...)
export const edgeFunctionName: string = (import.meta.env.VITE_EDGE_FN_NAME as string | undefined) || 'edge-function';

export const functionsBase = (projectId: string) => `https://${projectId}.supabase.co/functions/v1/${edgeFunctionName}`;